@startuml
!define Table(name,desc) class name as "desc" << (C,#FFAAAA) >>
!define primary_key(x) <b>x</b>
!define unique(x) <color:green>x</color>
!define not_null(x) <u>x</u>

       class com.kitku.primes.tests.AKSTest {
        static long c[] = new long[100];.
                static void coef(int n);
                static boolean isPrime(int n);
        }


@enduml
